services:
  - type: web
    name: aquaspot-analyzer
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
